### ISSUE TITLE
bareun 서비스 접속 오류에 대한 메시지 예외 분리 처리

### ISSUE THREAD

**Issue by gih2yun** [bareun-nlp/bareunpy#6]
### 문제점
- 대부분의 사용자들이 처음에 접속 오류를 경험하게 됩니다.
- 이 대부분은 grpc error 14, unavailable 입니다.

### 대응
- 예외코드 중에서 error 14가 나오게 되면, 이를 분할하여 사용자에게 알림을 정확하게 줍니다.
- 접속할 주소가 변수로 이미 있으므로 아래와 같은 메시지가 출력이 가능합니다.
- `{addr}에 있는 바른 서비스에 접속할 수 없습니다. 서비스가 실행중인지 확인하시거나 주소를 확인하세요.`

**Comment by gih2yun** [comment]
API KEY 오류에 대한 메시지도 더 명확하게 볼 수 있도록 처리하면 좋겠어요.

apikey가 이미 변수로 있을 것이니까요. 이것과 오류 메시지랑 함께 보여주면 좋겠습니다.

**Comment by YugwonWon** [comment]
@gih2yun 
* 오류인 경우 아래와 같이 나오면 될까요?
* apikey 오류인 경우 아래와 같이 출력하도록 수정

```
Traceback (most recent call last):
  File "/home/yugwon/bareunpy/bareunpy/_lang_service_client.py", line 104, in analyze_syntax_list
    res, c = self.stub.AnalyzeSyntaxList.with_call(
  File "/home/yugwon/bareunpy/venv/lib/python3.9/site-packages/grpc/_channel.py", line 957, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/home/yugwon/bareunpy/venv/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "API KEY가 정상적이지 않습니다: API key authentication failed"
        debug_error_string = "{"created":"@1699939876.694448210","description":"Error received from peer ipv4:127.0.0.1:5656","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"API KEY\u00ea\u00b0\u0080 \u00ec\u00a0\u0095\u00ec\u0083\u0081\u00ec\u00a0\u0081\u00ec\u009d\u00b4\u00ec\u00a7\u0080 \u00ec\u0095\u008a\u00ec\u008a\u00b5\u00eb\u008b\u0088\u00eb\u008b\u00a4: API key authentication failed","grpc_status":7}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yugwon/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yugwon/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/yugwon/bareunpy/testcli.py", line 6, in <module>
    res2 = tg.taglist(sents).msg()
  File "/home/yugwon/bareunpy/bareunpy/_tagger.py", line 250, in taglist
    raise e
  File "/home/yugwon/bareunpy/bareunpy/_tagger.py", line 247, in taglist
    res = self.client.analyze_syntax_list(phrase, self.domain, auto_spacing=auto_spacing, auto_jointing=auto_jointing)
  File "/home/yugwon/bareunpy/bareunpy/_lang_service_client.py", line 110, in analyze_syntax_list
    raise Exception(message) from e
Exception: 
입력한 API key가 정확한지 확인해 주세요.
 > apikey: koba-12345-ABCDE-12345-ABCDE
```

* 주소를 잘못 입력한 경우 아래와 같이 로그를 출력하도록 수정

```
Traceback (most recent call last):
  File "/home/yugwon/bareunpy/bareunpy/_lang_service_client.py", line 104, in analyze_syntax_list
    res, c = self.stub.AnalyzeSyntaxList.with_call(
  File "/home/yugwon/bareunpy/venv/lib/python3.9/site-packages/grpc/_channel.py", line 957, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/home/yugwon/bareunpy/venv/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for localhost:5656:5656: C-ares status is not ARES_SUCCESS qtype=AAAA name=localhost:5656:5656 is_balancer=0: Domain name not found"
        debug_error_string = "{"created":"@1699940223.022020858","description":"DNS resolution failed for localhost:5656:5656: C-ares status is not ARES_SUCCESS qtype=AAAA name=localhost:5656:5656 is_balancer=0: Domain name not found","file":"src/core/lib/transport/error_utils.cc","file_line":165,"grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yugwon/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yugwon/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/yugwon/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/yugwon/bareunpy/testcli.py", line 6, in <module>
    res2 = tg.taglist(sents).msg()
  File "/home/yugwon/bareunpy/bareunpy/_tagger.py", line 250, in taglist
    raise e
  File "/home/yugwon/bareunpy/bareunpy/_tagger.py", line 247, in taglist
    res = self.client.analyze_syntax_list(phrase, self.domain, auto_spacing=auto_spacing, auto_jointing=auto_jointing)
  File "/home/yugwon/bareunpy/bareunpy/_lang_service_client.py", line 113, in analyze_syntax_list
    raise Exception(message) from e
Exception: 
입력한 서버 주소가 정확한지 확인해 주세요.
 > host:port = localhost:5656:5656
```

**Comment by YugwonWon** [comment]
* PR #8
